Per turn operation
MadTurt1e/PicturePoker pull request #32
Opened 2024-03-01 21:49 UTC by MadTurt1e

Game has been updated  - this is the semi-functioning version of the game. 
Note arraylists have not been implemented in this - I find using them a little too "quirky". This can of course be changed in a potential future version. 
In any case, the core game elements have been implemented in this - 
#3 and #5 come to mind, as well as #17 (though that is not yet fully implemented). 

Once this PR is accepted, 
Closes #3
Closes #5

2024-03-01 22:18 UTC, jeffreyw2025 commented on src/main/java/game/jdbc/picturepoker/Game.java
Little miffed about the ArrayList thing, but should be fine as long as we have a method to sort. Take advantage of my comparison method!

2024-03-01 22:25 UTC, jeffreyw2025 requested changes
Most of the functionality seems fine, just some of the betting and payout logic needs refinement. See my comment on GamePlay.java.

2024-03-01 22:25 UTC, jeffreyw2025 commented on src/main/java/game/jdbc/picturepoker/GamePlay.java
I created a raise() function so there is a systematic way to handle betting, but I guess it's OK to just use it with a UI later on.

Bet logic is slightly bugged- it allows players to bet more coins than they have if they have fewer than 5 coins. Please fix this.

I created a dealer_cards table that should interface with the Game class. Are you sure it doesn't work?

The payout logic double-penalizes players if they fail. The method should return 0 if they lose to Luigi instead. However, I will say that the hand evaluation method is pretty clever, but do double-check some potential edge-cases just to make sure it works.

2024-03-01 22:41 UTC, MadTurt1e commented on src/main/java/game/jdbc/picturepoker/Game.java
absolutely right - I'll try using the compare function to do player order

2024-03-02 00:04 UTC, MadTurt1e commented
I've added player turns - this closes #4
Of course, we need to add some more fine-grained turn orders, but we really don't as the implementation adapts for this already.

2024-03-02 00:06 UTC, MadTurt1e commented on src/main/java/game/jdbc/picturepoker/GamePlay.java
Most functions mentioned have been implemented.

2024-03-02 00:06 UTC, MadTurt1e commented on src/main/java/game/jdbc/picturepoker/Game.java
Player order added

2024-03-02 21:59 UTC, jeffreyw2025 requested changes
Ok, this is super nitpicky, but the hand evaluation fails in a few scenarios. Consider the Player hand {Mushroom, Mushroom, Mushroom, Cloud, Cloud} vs the Luigi hand {Cloud, Cloud, Cloud, Star, Star}. By your logic, Player gets 4030 points (4000 for FH + 30 for 3 mushrooms) vs Luigi's 4100 (4000 for FH + 100 for stars), so the player would lose. However, the actual tiebreaker evaluates the three of a kinds first, so the Player would win. I know it's asking a lot but could you make sure the hand evaluation matches with the actual tiebreakers from the DS games?

2024-03-02 22:50 UTC, MadTurt1e commented
okay, done.

2024-03-02 23:28 UTC, jeffreyw2025 commented
I'm so sorry, Richard, but my grader instincts have given me another counterexample. Consider the Player hand {Star, Star, Cloud, Cloud, Mario} versus Luigi hand {Mario, Mario, Luigi, Luigi, Star}. The player strength evaluates to two pair + 40(6+1) vs Luigi's strength of two pair + 40(5+4), with the player losing again. However, the tiebreaker is to compare the stronger pairs first, so the player should win. I know I'm being really mean but I want this to be perfect. Make sure all the edge cases are fixed this time!

2024-03-02 23:37 UTC, MadTurt1e commented
Would it be possible for you to come up with an algorithm for point calculation?
 I have been working on the (relatively more pressing) update and delete functions and really cannot think of any reasonable ways to do point calculations and account for every edge case as of now, so a new perspective could be helpful in this scenario.
I appreciate it!

2024-03-03 03:25 UTC, closed without merging